services:
    gtb.api.view_handler.default:
        parent: fos_rest.view_handler.default
        calls:
            - ['registerHandler', ['json', [@gtb.api.view_handler.json_prefix, 'createResponse']]]

    gtb.api.view_handler.json_prefix:
        class: 'Gtb\Bundle\ApiBundle\View\JsonPrefixHandler'
        public: false

    kernel.event_listener.json_request_transformer:
        class: Qandidate\Common\Symfony\HttpKernel\EventListener\JsonRequestTransformerListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }
